apiVersion: "v1"
kind: "Service"
metadata:
  name: "group-pt-member"
  labels:
    app: "group-pt-member"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: "group-pt-member"
  type: "ClusterIP"