name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      
    - name: login docker hub
      uses: docker/login-action@v1
      with:
        registry: cylsh3452/sample
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push - member
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./group-pt-member/Dockerfile
        platforms: linux/amd64
        push: true
        tags: group-pt-member
        labels: $(date +%s)
        
    - name: Build and push - myclass
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./group-pt-myclass/Dockerfile
        platforms: linux/amd64
        push: true
        tags: group-pt-myclass
        labels: $(date +%s)
        
    - name: Build and push - reservation
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./group-pt-reservation/Dockerfile
        platforms: linux/amd64
        push: true
        tags: group-pt-reservation
        labels: $(date +%s)
