name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      
    - name: login docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build with docker - member
      run: docker build . --file ./group-pt-member/Dockerfile --tag cylsh3452/group-pt-member:latest
        
    - name: Push with docker - member
      run: docker push cylsh3452/group-pt-member:latest
      
    - name: Build with docker - myclass
      run: docker build . --file ./group-pt-myclass/Dockerfile --tag cylsh3452/group-pt-myclass:latest
        
    - name: Push with docker - myclass
      run: docker push cylsh3452/group-pt-myclass:latest
      
    - name: Build with docker - reservation
      run: docker build . --file ./group-pt-reservation/Dockerfile --tag cylsh3452/group-pt-reservation:latest
        
    - name: Push with docker - reservation
      run: docker push cylsh3452/group-pt-reservation:latest
